### PR TITLE
Doc missing network options

### LINKED ISSUE #365: Add kiln and ropsten as network options
Add kiln and ropsten as supported values for the `network` config option.

see https://github.com/ConsenSys/teku/pull/5514

### PR DESCRIPTION
**Pull request by alexandratran**
# Pull request checklist

Use the following template to make sure your PR fits the Teku documentation standard.

## Before creating the PR

Make sure that:

- [x] You've read the [contribution guidelines](https://consensys.net/docs/doctools/).
- [x] You've [previewed your changes locally](https://consensys.net/docs/doctools/en/latest/preview/old-system/#preview-locally).

## Describe the change

Add ropsten, kiln, gnosis, swift, and less-swift as supported values for the `network` option.

## Issue fixed

fixes #365 

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [ ] You've [fixed any issues](https://consensys.net/docs/doctools/en/latest/contribute/fix-cicd-errors/) raised by the tests.
- [ ] You've [previewed your changes on Read the Docs](https://consensys.net/docs/doctools/en/latest/preview/old-system/#preview-on-read-the-docs)
  and added a [preview link](#preview).

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM

**Review by bgravenorst — APPROVED** [review]
What's the difference between the 3 local dev networks? Otherwise LGTM

**Comment by alexandratran** [comment]
Keeping `swift` and `less-swift` omitted from the docs because they're only useful for internal acceptance tests. Users can use `minimal` for easy testing.

**Comment by rolfyone** [comment]
sounds fair, they're pretty limited usability anyway...

**Pull request merged**
