### PR TITLE
fix sentry nodes option

### PR DESCRIPTION
**Pull request by mehdi-aouadi**
Fix `sentry-config-file` option

### CODE REVIEW

**Review by StefanBratanov — COMMENTED** [review]
Should be `sentry-config-file: /etc/sentry-node-config.json` right?

**Comment by mehdi-aouadi** [comment]
> Should be `sentry-config-file: /etc/sentry-node-config.json` right?

My bad. Fixed it thanks!

**Review by StefanBratanov — APPROVED** [review]
lgtm

**Comment by StefanBratanov** [comment]
Actually wait think now need to fix in 23.12.1 as well.

**Pull request merged**
