### PR TITLE
Add docs for IPv6 support

### PR DESCRIPTION
**Pull request by StefanBratanov**
Related to https://github.com/Consensys/teku/issues/8069 and https://github.com/Consensys/teku/pull/8451

### CODE REVIEW

**Review by joaniefromtheblock — APPROVED** [review]
LGTM

**Comment by joaniefromtheblock** [comment]
Thank you @StefanBratanov

**Comment by joaniefromtheblock** [comment]
Please do not merge as yet. The team has to do some internal testing of the functionality before this can go in.

**Review by alexandratran — APPROVED** [review]
Minor edits, including moving the IPv6 page into the "Find and connect" section. LGTM.

**Pull request merged**
