### PR TITLE
docs: Fix Homebrew teku installation instruction

### PR DESCRIPTION
**Pull request by terorie**
## Pull request checklist

Use the following list to make sure your PR fits the Teku doc quality standard.

### Before creating the pull request

Make sure that:

- [x] you have read the [contribution guidelines](https://github.com/ConsenSys/doc.common/wiki/Contributing-to-Documentation).
- [x] you have [tested your changes locally](https://github.com/ConsenSys/doc.common/wiki/MkDocs-And-Custom-Markdown-Guide#preview-documentation-site-locally) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you have fixed all the issues raised by the tests, if any.
- [x] you have verified the rendering of your changes on
  [ReadTheDocs.org PR preview](https://github.com/ConsenSys/doc.common/wiki/MkDocs-And-Custom-Markdown-Guide#preview-the-doc-site-for-your-pr-on-readthedocscom)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Teku is now available in `homebrew-core`: https://formulae.brew.sh/formula/teku

The `ConsenSys/teku` tap is no longer required.

- Add `brew services` to upstream tap
- Use correct version of Gradle (Gradle wrapper)
- Fix version number printing

## Issue fixed

NA

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

https://pegasys-teku--324.com.readthedocs.build/en/324/HowTo/Get-Started/Installation-Options/Install-Binaries/

### CODE REVIEW

**Comment by ajsutton** [comment]
Working through some issues before we recommend using the core formula in https://github.com/Homebrew/homebrew-core/pull/92110

**Comment by ajsutton** [comment]
We got the key fixes for the teku formula merged into homebrew-core but I'm still not entirely sure I'd make it the recommended version as updates will be slower getting into homebrew than via our tap.  I was also able to add `brew services` support to our tap which upstream was rejecting so I think it is worth continuing to maintain and recommend our tap.

It's still good that if users just run `brew install teku` it will work and should get them a good version. If we get a bit more experience with it then it may be worth recommending that in the future.

In the meantime though to use our tap I think you now need to use the full name as part of `brew install` so it becomes `brew install Consensys/teku/teku` (the duplicate teku is an odd quirk of how brew works).

**Comment by terorie** [comment]
Apologies for breaking stuff. Amended this PR to fix the `brew install` instructions.

**Comment by NicolasMassart** [comment]
@terorie your Teku doc PR is pending merge because we need you to sign the CLA.
The link to sign is https://cla-assistant.io/ConsenSys/doc.teku?pullRequest=324
Once done, it will make your contribution ready to be merged in the official doc.
Thanks for contributing!

**Review by rolandtyler — APPROVED** [review]

**Pull request merged**
