### PR TITLE
Make sentry nodes a supported feature

### PR DESCRIPTION
**Pull request by ajsutton**
## Describe the change
Updates docs for sentry nodes to make them a fully supported feature.

## Issue fixed

https://github.com/ConsenSys/teku/issues/6459

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [ ] You've [fixed any issues](https://consensys.net/docs/doctools/en/latest/contribute/fix-cicd-errors/) raised by the tests.
- [ ] You've [previewed your changes on Read the Docs](https://consensys.net/docs/doctools/en/latest/preview/old-system/#preview-on-read-the-docs)
  and added a [preview link](#preview).

### CODE REVIEW

**Comment by ajsutton** [comment]
We want the 22.12.0 release to go out before we actually merge this. Just getting things prepped.

**Comment by ajsutton** [comment]
Ok 22.10.0 release is out and the change to make this supported has been merged into Teku, so this is ready for review and merge.

**Review by rolandtyler — APPROVED** [review]
@ajsutton, I added the `sentry-config-file` option to the CLI reference page. If you're okay with the content, everything else LGTM, and is okay to merge.

**Comment by ajsutton** [comment]
Oh yeah, good spot. Thanks.

**Pull request merged**
